### ISSUE TITLE
ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'RPC Response'. java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by albertoaus** [jlavallee/JMeter-Rabbit-AMQP#45]
Hi, I'm using your plugin to do some tests, thank you very much for sharing it because it is a good job. I think I have found a bug when a user uses a consumer in an auto delete queue.In my tests I have the queue with one message (see rabbitMQ picture) and after execute the AMQP Consumer in JMeter, the message is consumed but there is an error in JMeter and I can not see the result of the response.

![image](https://user-images.githubusercontent.com/5541342/28420505-a947da8a-6d62-11e7-8cfe-c5a66183f0e3.png)

![image](https://user-images.githubusercontent.com/5541342/28420567-d7f92bb8-6d62-11e7-8f79-c6d768d9898a.png)

**Logs with Error Response**
> 2017-07-20 15:48:06,446 INFO c.z.j.p.a.g.AMQPSamplerGui: AMQPSamplerGui.modifyTestElement() called, set user/pass to guest/guest on sampler com.zeroclue.jmeter.protocol.amqp.AMQPConsumer@991d1c
2017-07-20 15:48:06,446 INFO c.z.j.p.a.g.AMQPSamplerGui: AMQPSamplerGui.configure() called
2017-07-20 15:48:06,447 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2017-07-20 15:48:06,448 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2017-07-20 15:48:06,448 INFO o.a.j.g.u.JMeterMenuBar: setRunning(true, *local*)
2017-07-20 15:48:06,458 INFO o.a.j.e.StandardJMeterEngine: Starting ThreadGroup: 1 : Thread Group
2017-07-20 15:48:06,458 INFO o.a.j.e.StandardJMeterEngine: Starting 1 threads for group Thread Group.
2017-07-20 15:48:06,458 INFO o.a.j.e.StandardJMeterEngine: Thread will continue on error
2017-07-20 15:48:06,458 INFO o.a.j.t.ThreadGroup: Starting thread group... number=1 threads=1 ramp-up=1 perThread=1000.0 delayedStart=false
2017-07-20 15:48:06,458 INFO o.a.j.t.ThreadGroup: Started thread group number 1
2017-07-20 15:48:06,458 INFO o.a.j.e.StandardJMeterEngine: All thread groups have been started
2017-07-20 15:48:06,459 INFO o.a.j.t.JMeterThread: Thread started: Thread Group 1-1
2017-07-20 15:48:06,460 INFO c.z.j.p.a.AMQPSampler: Creating channel /:5672
2017-07-20 15:48:06,460 INFO c.z.j.p.a.AMQPSampler: RabbitMQ ConnectionFactory using:
	 virtual host: /
	 host: localhost
	 port: 5672
	 username: guest
	 password: guest
	 timeout: 1000000
	 heartbeat: 1
in com.zeroclue.jmeter.protocol.amqp.AMQPConsumer@d9dbffd
2017-07-20 15:48:06,460 INFO c.z.j.p.a.AMQPSampler: Using hosts: [localhost] addresses: [localhost:5672]
2017-07-20 15:48:07,491 INFO c.z.j.p.a.AMQPSampler: bound to:
	 queue: rpc-queue-reply-test
	 exchange: 
	 exchange(D)? false
	 routing key: rpc-queue-reply-test
	 arguments: {}
2017-07-20 15:48:07,492 INFO c.z.j.p.a.AMQPConsumer: Creating consumer
2017-07-20 15:48:07,492 INFO c.z.j.p.a.AMQPConsumer: Starting basic consumer
2017-07-20 15:48:07,495 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'RPC Response'.
java.lang.NullPointerException: null
	at com.zeroclue.jmeter.protocol.amqp.AMQPConsumer.formatHeaders(AMQPConsumer.java:357) ~[JMeterAMQP.jar:?]
	at com.zeroclue.jmeter.protocol.amqp.AMQPConsumer.sample(AMQPConsumer.java:122) ~[JMeterAMQP.jar:?]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:491) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:425) [ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:254) [ApacheJMeter_core.jar:3.2 r1790748]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
2017-07-20 15:48:07,496 INFO o.a.j.t.JMeterThread: Thread is done: Thread Group 1-1
2017-07-20 15:48:07,496 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group 1-1
2017-07-20 15:48:07,496 INFO c.z.j.p.a.AMQPSampler: AMQPSampler.threadFinished called
2017-07-20 15:48:07,510 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2017-07-20 15:48:07,510 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)

**Comment by itsikb** [comment]
See here for a solution:
https://github.com/jlavallee/JMeter-Rabbit-AMQP/issues/41
